

import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';



part 'gratitude_entry.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0) // Unique typeId for this model
class GratitudeEntry extends HiveObject {


  @HiveField(0) // Index 0
  late String id;

  @HiveField(1) // Index 1
  late String text;

  @HiveField(2) // Index 2
  late DateTime timestamp;

  GratitudeEntry({
    required this.text,
    required this.timestamp,
  }) {

    id = const Uuid().v4();
  }
}